apiVersion: v1
kind: Service
metadata:
  name: dotnetcoreapp
  namespace: ${NAMESPACE}
  labels:
    app: dotnetcoreapp
    environment: ${ENVIRONMENT}
spec:
  type: ClusterIP
  selector:
    app: dotnetcoreapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
