name: 'Test .NET Application'
description: 'Runs .NET tests with optional code coverage reporting'
author: 'Architecture Team'

inputs:
  test-path:
    description: 'Path to test project file or directory'
    required: true
  configuration:
    description: 'Test configuration (Debug/Release)'
    required: false
    default: 'Release'
  collect-coverage:
    description: 'Collect code coverage data'
    required: false
    default: 'true'
  verbosity:
    description: 'Test output verbosity (quiet|minimal|normal|detailed|diagnostic)'
    required: false
    default: 'normal'

outputs:
  coverage-path:
    description: 'Path to coverage report'
    value: ${{ steps.test.outputs.coverage-path }}
  test-results-path:
    description: 'Path to test results'
    value: ${{ steps.test.outputs.test-results-path }}

runs:
  using: "composite"
  steps:
    - name: Run tests
      id: test
      shell: bash
      env:
        TEST_PATH: ${{ inputs.test-path }}
        CONFIGURATION: ${{ inputs.configuration }}
        VERBOSITY: ${{ inputs.verbosity }}
        COLLECT_COVERAGE: ${{ inputs.collect-coverage }}
      run: |
        # Create test results directory
        mkdir -p TestResults

        # Execute tests with or without coverage collection
        if [ "$COLLECT_COVERAGE" == "true" ]; then
          dotnet test "$TEST_PATH" \
            --configuration "$CONFIGURATION" \
            --no-build \
            --verbosity "$VERBOSITY" \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory TestResults \
            --collect:"XPlat Code Coverage"
        else
          dotnet test "$TEST_PATH" \
            --configuration "$CONFIGURATION" \
            --no-build \
            --verbosity "$VERBOSITY" \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory TestResults
        fi

        # Set outputs
        echo "test-results-path=TestResults" >> $GITHUB_OUTPUT
        echo "coverage-path=TestResults/*/coverage.cobertura.xml" >> $GITHUB_OUTPUT

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/*.trx
        retention-days: 30

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always() && inputs.collect-coverage == 'true'
      with:
        name: coverage-reports
        path: TestResults/*/coverage.cobertura.xml
        retention-days: 30
